name: Set up Conda environment
inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml
runs:
  using: composite
  steps:
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'  # You can adjust the Python version as needed
        auto-update-conda: true
        environment-file: ${{ inputs.environment-file }}
        activate-environment: test