[tool.poetry]
name = "krv_analytics"
version = "0.1.0"
description = ""
authors = [
    "jeremy.wayland <jeremy.don.wayland@gmail.com>",
    "stuart.wayland <swayland@ucsc.edu>",
    "sid.gathrid <sgathrid@yahoo.com>",
]
readme = "README.md"
packages = [{ include = "krv_mapper" }]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.2"
networkx = "^3.0"
black = "^23.1.0"
pandas = "^1.5.3"
jupyter = "^1.0.0"
matplotlib = "^3.6.3"
pymongo = "^4.3.3"
cython = "^0.29.33"
ripser = "^0.6.4"
persim = "^0.3.1"
fastapi = "^0.91.0"
python-dotenv = "^0.21.1"
uvicorn = "^0.20.0"
pot = "^0.8.2"
pytest = "^7.2.1"
yaspin = "^2.3.0"
datetime = "^5.0"
kmapper = "^2.0.1"
scikit-learn = "^1.2.1"
seaborn = "^0.12.2"
giotto-tda = "^0.6.0"
hdbscan = "^0.8.29"
python-log-indenter = "^0.9"
numba = "^0.57.1"
tqdm = "^4.65.0"
umap-learn = "^0.5.3"

urllib3 = "1.26.16"
category-encoders = "^2.6.1"
shyaml = "^0.6.2"
omegaconf = "^2.3.0"

[tool.poetry.group.dev.dependencies]
kmapper = "^2.0.1"
ipykernel = "^6.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
