[tool.poetry]
name = "coal-mapper"
version = "0.1.0"
description = ""
authors = ["jeremy.wayland <jeremy.don.wayland@gmail.com>"]
readme = "README.md"
packages = [{ include = "coal_mapper" }]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.2"
networkx = "^3.0"
black = "^23.1.0"
pandas = "^1.5.3"
jupyter = "^1.0.0"
matplotlib = "^3.6.3"
pymongo = "^4.3.3"
cython = "^0.29.33"
ripser = "^0.6.4"
persim = "^0.3.1"
fastapi = "^0.91.0"
python-dotenv = "^0.21.1"
uvicorn = "^0.20.0"
pot = "^0.8.2"
pytest = "^7.2.1"
sklearn = "^0.0.post1"
yaspin = "^2.3.0"
datetime = "^5.0"
kmapper = "^2.0.1"
scikit-learn = "^1.2.1"
seaborn = "^0.12.2"
giotto-tda = "^0.6.0"

[tool.poetry.group.dev.dependencies]
kmapper = "^2.0.1"
ipykernel = "^6.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
