""" Use Ollivier Ricci curvature + TDA to analyze a set of Mappers generated by a hyperparameter grid search."""

import argparse
import sys
import os
import pickle

from parameter_clustering_helper import cluster_hyperparams, read_distance_matrices

cwd = os.path.dirname(__file__)

if __name__ == "__main__":

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-m",
        "--metric",
        type=str,
        default="landscape",
        help="Select metric (that is supported by Giotto) to compare persistence daigrams.",
    )

    parser.add_argument(
        "--p_frac",
        type=float,
        default=0.25,
        help="Fraction of Labels to see in dendrogram plot.",
    )

    parser.add_argument(
        "-s",
        "--save",
        default=True,
        help="If True, save the clustering model and distances as pickle files.",
    )

    parser.add_argument(
        "-v",
        "--Verbose",
        default=False,
        action="store_true",
        help="If set, will print messages detailing computation and output.",
    )

    args = parser.parse_args()
    this = sys.modules[__name__]

    # Read in Keys and distances from pickle file

    keys, distances = read_distance_matrices(args.metric)
    model = cluster_hyperparams(keys, distances, p_frac=args.p_frac, metric=args.metric)

    results = {"keys": keys, "model": model}
    if args.save:
        model_file = f"curvature_{args.metric}_clustering_model.pkl"

        out_dir_message = f"{model_file} successfully written."

        output_dir = os.path.join(cwd, "../../../data/parameter_modeling/models/")

        # Check if output directory already exists
        if os.path.isdir(output_dir):
            model_file = os.path.join(output_dir, model_file)

        else:
            os.makedirs(output_dir, exist_ok=True)
            model_file = os.path.join(output_dir, model_file)
        with open(model_file, "wb") as handle:
            pickle.dump(results, handle, protocol=pickle.HIGHEST_PROTOCOL)

        if args.Verbose:
            print("\n")
            print(
                "-------------------------------------------------------------------------------- \n\n"
            )
            print(f"{out_dir_message}")

            print(
                "\n\n -------------------------------------------------------------------------------- "
            )
