runName: demoFiles
data: /Users/gathrid/Repos/thema_light/Thema/docs/source/userGuides/demoFiles/breastCancer.pkl
outDir: /Users/gathrid/Repos/thema_light/Thema/docs/source/userGuides/
Planet:
  scaler: standard
  encoding: one_hot
  dropColumns: None
  imputeColumns: None
  imputeMethods: None
  numSamples: 1
  seeds: auto

Oort:
  umap:
    nn:
    - 5
    - 10
    - 50
    minDist:
    - 0.05
    - 0.1
    - 0.15
    - 0.5
    dimensions:
    - 2
    seed:
    - 32
    - 50
  projectiles:
    - umap

Galaxy:
  metric: stellar_kernel_distance
  selector: random
  nReps: 2
  stars:
    - jmap 
  jmap:
    nCubes:
    - 2
    - 5
    - 15
    - 30
    percOverlap:
    - 0.05
    - 0.1
    - 0.5
    minIntersection:
    - -1
    clusterer:
    - [HDBSCAN, {min_cluster_size: 2}] 
    - [HDBSCAN, {min_cluster_size: 5}] 
    - [HDBSCAN, {min_cluster_size: 10}] 