name: Run Tests and Report Results
description: Set up the Conda environment and run tests using pytest.

inputs:
  environment-file:
    description: The Conda environment file to use.
    required: true
    default: environment.yml

runs:
  using: composite
  steps:
    - name: Set up Conda
      uses: ../setup-conda 
      with:
        environment-file: ${{ inputs.environment-file }}
        activate-environment: test
